Locales ['hr'] = {
  ['valid_purchase'] = 'Potvrdite kupnju',
  ['yes'] = 'Da (<span style="color: green;">$%s</span>)',
  ['no'] = 'Ne',
  ['helmet'] = 'Kaciga / kapa',
  ['glasses'] = 'Naocale',
  ['mask'] = 'Maska',
  ['ears'] = 'Naušnice',
  ['shop'] = '%s trgovina',
  ['set_unset'] = 'Stavi / makni',
  ['not_enough_money'] = 'Nemaš dovoljno novaca',
  ['press_access'] = 'Pritisni ~INPUT_CONTEXT~ da otvoris meni',
  ['accessories_blip'] = 'Dodatci',
  ['no_ears'] = 'Nemaš naušnice',
  ['no_glasses'] = 'Nemaš naocale',
  ['no_helmet'] = 'Nemaš kacigu',
  ['no_mask'] = 'Nemaš masku',
  ['you_paid'] = 'Platio si ~g~$%s~s~',
}
