Locales['hr'] = {
  ['have_withdrawn'] = 'Podigao si ~y~x%s~s~ ~b~%s~s~',
  ['have_deposited'] = 'Stavio si ~y~x%s~s~ ~b~%s~s~',
  ['free_prop'] = 'Posjed na prodaju',
  ['property'] = 'Posjed',
  ['enter'] = 'Udi',
  ['move_out'] = 'Preseli se',
  ['move_out_sold'] = 'Prodaj posjed za <span style="color:green;">$%s</span>',
  ['moved_out'] = 'Odselio si se i više ne placas najamninu.',
  ['moved_out_sold'] = 'Prodao si posjed za ~g~$%s~s~',
  ['buy'] = 'Kupi posjed za <span style="color:green;">$%s</span>',
  ['buy_for'] = 'Kupio si posjed za ~g~$%s~s~',
  ['rent'] = 'Unajmi posjed za <span style="color:green;">$%s</span> / tjedan',
  ['rent_for'] = 'Unajmio si posjed za ~g~$%s~s~ / tjedan, placanje je automatsko',
  ['press_to_menu'] = 'Pritisni ~INPUT_CONTEXT~ da pristupis ~y~Meniu Posjeda~s~.',
  ['owned_properties'] = 'Posjedi u vlasništvu',
  ['available_properties'] = 'Slobodni posjedi',
  ['invite_player'] = 'Pozovi covjeka',
  ['you_invited'] = 'Pozvao si ~y~%s~s~ na vaš posjed',
  ['player_clothes'] = 'Odjela',
  ['remove_cloth'] = 'Makni odjelo',
  ['removed_cloth'] = 'Odjelo je maknuto iz ormara!',
  ['remove_object'] = 'Makni objekt',
  ['deposit_object'] = 'Stavi objekt',
  ['invite'] = 'Pozovi',
  ['dirty_money'] = 'Prljav novac: <span style="color:red;">$%s</span>',
  ['inventory'] = 'Inventar',
  ['amount'] = 'Kolicina?',
  ['amount_invalid'] = 'Kriva kolicina',
  ['press_to_exit'] = 'Pritisni ~INPUT_CONTEXT~ da izades sa posjeda',
  ['not_enough'] = 'Nemas dovoljno novaca',
  ['invalid_quantity'] = 'Kriva kolicina',
  ['paid_rent'] = 'Platio si najam ~g~$%s~s~ za ~y~%s~s~',
  ['paid_rent_evicted'] = 'Potjeran si ~o~sa svojeg posjeda~s~ sa ~y~%s~s~ zbog ne placanja najma od ~g~$%s~s~',
  ['not_enough_in_property'] = 'Nema dovoljno ~r~te stvari~s~ na posjedu!',
  ['player_cannot_hold'] = 'Nemaš ~r~dovoljno~s~ ~y~slobodnog mjesta~s~ u inventaru!',
}
