Locales['hr'] = {
  -- Cloakroom
  ['cloakroom'] = 'Svlacionica',
  ['ems_clothes_civil'] = 'Civilno odjelo',
  ['ems_clothes_ems'] = 'EMS Odjelo',
  -- Vehicles
  ['ambulance'] = 'Hitna Pomoc',
  ['helicopter_prompt'] = 'Pritisni ~INPUT_CONTEXT~ da pristupis ~y~Helicopter Meniu~s~.',
  ['garage_prompt'] = 'Pritisni ~INPUT_CONTEXT~ da pristupis ~y~Vozilo Meniu~s~.',
  ['garage_title'] = 'Vozilo meni',
  ['garage_stored'] = 'Spremljeno',
  ['garage_notstored'] = 'Nije u garaži',
  ['garage_storing'] = 'Spremamo vozilo u garažu.',
  ['garage_has_stored'] = 'Vozilo je spremljeno u garažu',
  ['garage_has_notstored'] = 'Nema vozila EMSa u blizini',
  ['garage_notavailable'] = 'Vaše vozilo nije spremljeno u garaži',
  ['garage_blocked'] = 'Nema dostupnih spawn mjesta',
  ['garage_empty'] = 'Nema vozila u garaži',
  ['garage_released'] = 'Vozilo je van garaže',
  ['garage_store_nearby'] = 'Nema vozila u blizini.',
  ['garage_storeditem'] = 'Otvori garažu',
  ['garage_storeitem'] = 'Spremi vozilo u garažu',
  ['garage_buyitem'] = 'Autosalon EMS',
  ['shop_item'] = '$%s',
  ['vehicleshop_title'] = 'Autosalon EMS',
  ['vehicleshop_confirm'] = 'Kupite vozilo?',
  ['vehicleshop_bought'] = 'Kupio si ~y~%s~s~ za ~g~$%s~s~',
  ['vehicleshop_money'] = 'Ne mozes si priuštiti',
  ['vehicleshop_awaiting_model'] = 'Vozilo se ~g~skida i ucitava~s~',
  ['confirm_no'] = 'Ne',
  ['confirm_yes'] = 'Da',
  -- Action Menu
  ['revive_inprogress'] = 'Oživljavanje u procesu!',
  ['revive_complete'] = 'Dobio si ~y~%s~s~',
  ['revive_complete_award'] = 'Primio si ~y~%s~s~ i dobio ~g~$%s~s~!',
  ['revive_fail_offline'] = 'Igrac nije online vise',
  ['heal_inprogress'] = 'Izljecujes!',
  ['heal_complete'] = 'Izljecio si ~y~%s~s~',
  ['no_players'] = 'Nema ljudi u blizini',
  ['player_not_unconscious'] = 'Covjek je u nesvjesti!',
  ['player_not_conscious'] = 'Covjek je pri svjesti!',
  -- Boss Menu
  ['boss_actions'] = 'Boss Meni',
  -- Misc
  ['invalid_amount'] = '~r~Kriva kolicina',
  ['actions_prompt'] = 'Pritisni ~INPUT_CONTEXT~ da pristupis ~y~EMS Akcijama~s~.',
  ['deposit_amount'] = 'Stavi',
  ['money_withdraw'] = 'Podigni',
  ['fast_travel'] = 'Pritisni ~INPUT_CONTEXT~ da se fast travelate.',
  ['open_pharmacy'] = 'Pritisni ~INPUT_CONTEXT~ da otvoriš ljekarnu.',
  ['pharmacy_menu_title'] = 'Ljekarna',
  ['pharmacy_take'] = 'Uzmi <span style="color:blue;">%s</span>',
  ['medikit'] = 'Medkit',
  ['bandage'] = 'Bandaža',
  ['max_item'] = 'Vec imas taj item.',
  -- F6 Menu
  ['ems_menu'] = 'EMS Meni',
  ['ems_menu_title'] = 'EMS - Meni',
  ['ems_menu_revive'] = 'Oživite covjeka',
  ['ems_menu_putincar'] = 'Stavi u vozilo',
  ['ems_menu_small'] = 'Izljeci rane',
  ['ems_menu_big'] = 'Njegujte velike rane',
  -- Phone
  ['alert_ambulance'] = 'alert Ambulance',
  -- Death
  ['respawn_available_in'] = 'Respawn dostupan za ~b~%s min %s sec~s~',
  ['respawn_bleedout_in'] = 'Iskrvarit ces za ~b~%s min %s sec~s~\n',
  ['respawn_bleedout_prompt'] = 'Drži [~b~E~s~] da se respawnaš',
  ['respawn_bleedout_fine'] = 'Drži [~b~E~s~] da se respawnaš za ~g~$%s~s~',
  ['respawn_bleedout_fine_msg'] = 'Platio si ~r~$%s~s~ da se respawnaš.',
  ['distress_send'] = 'Pritisni [~b~G~s~] da posaljes signal EMSu',
  ['distress_sent'] = 'Signal je poslan!',
  ['combatlog_message'] = 'Force respawnao si se jer si se combatlogao.',
  -- Revive
  ['revive_help'] = 'Ozivi igraca',
  -- Item
  ['used_medikit'] = 'Iskoristio si ~y~1x~s~ medkit',
  ['used_bandage'] = 'Iskoristio si ~y~1x~s~ bandazu',
  ['not_enough_medikit'] = 'Nemaš ~b~medkit~s~.',
  ['not_enough_bandage'] = 'Nemaš ~b~bandazu~s~.',
  ['healed'] = 'Izljecen si.',
  -- Blips
  ['blip_hospital'] = 'Bolnica',
  ['blip_dead'] = 'Onesvješten covjek',
}
