Locales['br'] = {
    -- Cloakroom
    ['cloakroom'] = 'Soba za presvlacenje',
    ['jail'] = 'Zatvor',
    ['citizen_wear'] = 'Civilno odijelo',
    ['mafija_wear'] = 'mafija odijelo',
    ['gilet_wear'] = 'Narandzasta reflektujuca jakna',
    ['bullet_wear'] = 'Pancir',
    ['no_outfit'] = 'there\'s no uniform that fits you!',
    ['open_cloackroom'] = 'Pritisnite ~INPUT_CONTEXT~ da promijenite ~y~odjeću~s~.',
    -- Armory
    ['remove_object'] = 'Makni objekt',
    ['deposit_object'] = 'ostavi objekt',
    ['get_weapon'] = 'Uzmi oružije',
    ['put_weapon'] = 'Ostavi oružije',
    ['idsearch'] = 'mafija Vam gleda identitet',
    ['revista'] = 'mafija Vas pretražuje',
    ['buy_weapons'] = 'Kupi oružije',
    ['armory'] = 'Oružarnica',
    ['venda'] = 'Stavi vrecicu na glavu',
    ['open_armory'] = 'Pritisnite ~INPUT_CONTEXT~ da pristupite oružarnici',
    -- Vehicles
    ['vehicle_menu'] = 'vozilo',
    ['vehicle_out'] = 'Vozilo je van garaže',
    ['vehicle_spawner'] = 'Pritisnite ~INPUT_CONTEXT~ da spawnate vozilo',
    ['store_vehicle'] = 'Pritisnite ~INPUT_CONTEXT~ da ostavis vozilo',
    -- Service
    ['service_max'] = 'ne mozete pristupiti sluzbi, maksimalan broj sluzbenika: %s/%s',
    ['service_not'] = 'you have not entered service! You\'ll have to get changed first.',
    ['service_anonunce'] = 'servis informacije',
    ['service_in'] = 'pristupio si servisu, dobrodosao!',
    ['service_in_announce'] = 'operator ~y~%s~s~ je pristupio sluzbi!',
    ['service_out'] = 'izasao si iz sluzbe',
    ['service_out_announce'] = 'operator ~y~%s~s~ je otisao iz sluzbe.',
    -- Action Menu
    ['citizen_interaction'] = 'interakcija gradjana',
    ['vehicle_interaction'] = 'interakcija vozila',
    ['object_spawner'] = 'stvori objekat',
  
    ['id_card'] = 'ID Karta',
    ['search'] = 'Pretrazi',
    ['handcuff'] = 'Zaveži / Odveži',
    ['drag'] = 'Vuci',
    ['put_in_vehicle'] = 'Stavi u vozilo',
    ['out_the_vehicle'] = 'Izvadi iz vozila',
    ['fine'] = 'Kazne',
    ['unpaid_bills'] = 'upravljaj neplacenim racunima',
    ['license_check'] = 'upravljaj licencom',
    ['license_revoke'] = 'oduzmi licencu',
    ['license_revoked'] = 'tvoja ~b~%s~s~ je ~y~revoked~s~!',
    ['licence_you_revoked'] = 'Oduzeo si ~b~%s~s~ koja je pripadala ~y~%s~s~',
    ['no_players_nearby'] = 'Nema igraca u blizini!',
    ['being_searched'] = '~y~Pretraženi ste~s~ od strane ~g~mafijaa~s~',
    -- Vehicle interaction
    ['vehicle_info'] = 'Info vozila',
    ['pick_lock'] = 'Obite vozilo',
    ['vehicle_unlocked'] = 'Vozilo je ~g~otkljucano~s~',
    ['no_vehicles_nearby'] = 'Nema vozila u blizini',
    ['impound'] = 'Zapljenite vozilo',
    ['impound_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da prestanete sa ~y~zapljenom~s~',
    ['impound_canceled'] = 'Zapljena je prekinuta',
    ['impound_canceled_moved'] = 'Zapljena je prekinuta jer se vozilo pomaknulo',
    ['impound_successful'] = 'Oduzeli ste vozilo',
    ['search_database'] = 'Informacije o vozilu',
    ['search_database_title'] = 'Informacije o vozilu - pretrazite sa registarskim tablicama',
    ['search_database_error_invalid'] = 'Ovo ~r~nije~s~ ~y~tocna~s~ registracija',
    ['search_database_error_not_found'] = 'Ta ~y~tablica~s~ ~r~nije~s~ registrirana niti na jedno vozilo!',
    ['search_database_found'] = 'Vozilo je ~y~u vlasništvu~s~ ~b~%s~s~',
    -- Traffic interaction
    ['traffic_interaction'] = 'Prometna Interakcija',
    ['cone'] = 'Cunj',
    ['barrier'] = 'Barijera',
    ['spikestrips'] = 'Šiljasta traka',
    --['box'] = 'kutija',
    --['cash'] = 'kutija sa novcem',
    -- ID Card Menu
    ['name'] = 'Ime: %s',
    ['job'] = 'Posao: %s',
    ['sex'] = 'Pol: %s',
    ['dob'] = 'Datum rodjenja: %s',
    ['height'] = 'Visina: %s',
    ['id'] = 'ID: %s',
    ['bac'] = 'BAC: %s',
    ['unknown'] = 'Nepoznato',
    ['male'] = 'Muško',
    ['female'] = 'Žensko',
    -- Body Search Menu
    ['guns_label'] = '--- Oružije ---',
    ['inventory_label'] = '--- Inventar ---',
    ['license_label'] = ' --- Licence ---',
    ['confiscate'] = 'Oduzeti %s',
    ['confiscate_weapon'] = 'Oduzeto %s sa %s metaka',
    ['confiscate_inv'] = 'Oduzeto %sx %s',
    ['confiscate_dirty'] = 'Oduzeto prljavog novca: <span style="color:red;">$%s</span>',
    ['you_confiscated'] = 'Oduzeli ste ~y~%sx~s~ ~b~%s~s~ od ~b~%s~s~',
    ['got_confiscated'] = '~y~%sx~s~ ~b~%s~s~ je oduzeto od ~y~%s~s~',
    ['you_confiscated_account'] = 'Oduzeli ste ~g~$%s~s~ (%s) od ~b~%s~s~',
    ['got_confiscated_account'] = '~g~$%s~s~ (%s) je oduzeo od ~y~%s~s~',
    ['you_confiscated_weapon'] = 'Oduzeli ste ~b~%s~s~ od ~b~%s~s~ sa ~o~%s~s~ metaka',
    ['got_confiscated_weapon'] = 'Vaša ~b~%s~s~ sa ~o~%s~s~ metaka je oduzeta od strane ~y~%s~s~',
    ['traffic_offense'] = 'Prometni prekršaj',
    ['minor_offense'] = 'Manji Prekrsaj',
    ['average_offense'] = 'Osnovan Prektsaj',
    ['major_offense'] = 'Ozbiljan Prekrsaj',
    ['fine_total'] = 'Kazna: %s',
    -- Vehicle Info Menu
    ['plate'] = 'Tablice: %s',
    ['owner_unknown'] = 'Vlasnik: Nepoznat',
    ['owner'] = 'Vlasnik: %s',
    -- Weapons Menus
    ['get_weapon_menu'] = 'Oruzarnica - Uzmite Oruzije',
    ['put_weapon_menu'] = 'Oruzarnica - Ostavite Oruzije',
    ['buy_weapon_menu'] = 'Oruzarnica - Kupite Oruzije',
    ['not_enough_money'] = 'Nemate dovoljno novca',
    -- Boss Menu
    ['take_company_money'] = 'Uzmite novac iz sefa',
    ['deposit_money'] = 'Ostavite Novac',
    ['amount_of_withdrawal'] = 'Kolicina novca',
    ['invalid_amount'] = 'Nevazeca Kolicina',
    ['amount_of_deposit'] = 'Kolicina za ostavljanje',
    ['open_bossmenu'] = 'Pritisnite ~INPUT_CONTEXT~ da otvorite meni',
    ['quantity_invalid'] = 'Nevazeca kolicina',
    ['have_withdrawn'] = 'Uzeli ste ~y~%sx~s~ ~b~%s~s~',
    ['have_deposited'] = 'Ostavili ste ~y~%sx~s~ ~b~%s~s~',
    ['quantity'] = 'Kolicina',
    ['inventory'] = 'Inventar',
    ['mafija_stock'] = 'Policajske Zalihe',
    -- Misc
    ['remove_prop'] = 'Pritisnite ~INPUT_CONTEXT~ da obrisete objekat',
    ['map_blip'] = 'Policijska postaja',
    ['unrestrained_timer'] = 'Osecate da se llisice polako otvaraju i spadaju sa ruku',
    -- Notifications
    ['alert_mafija'] = 'Upozorenje',
    ['phone_mafija'] = 'mafija',
  }
  
  