Locales['hr'] = {
  -- Global menus
  ['cloakroom'] = 'Svlacionica',
  ['cloak_change'] = 'Pritisni ~INPUT_PICKUP~ da promijenis odjecu.',
  ['citizen_wear'] = 'Civilna odjeca',
  ['job_wear'] = 'Radna odjeca',
  ['bank_deposit_returned'] = 'Siguran depozit od ~g~$%s~s~ je vracen.',
  ['bank_deposit_taken'] = 'Siguran depozit od ~r~$%s~s~ je oduzet.',
  ['caution_afford'] = 'Ne možeš si priuštiti kauciju od ~g~$%s~s~',
  ['foot_work'] = 'Moraš biti izvan vozila.',
  ['next_point'] = 'Otidi na drugu lokaciju nakon ovog.',
  ['not_your_vehicle'] = 'Nisi vozac ovog vozila.',
  ['in_vehicle'] = 'Moras biti u vozilu.',
  ['wrong_point'] = 'Nisi na pravoj lokaciji.',
  ['max_limit'] = 'Ne možeš nositi više ~y~%s~s~',
  ['not_enough'] = 'Nemaš dovoljno ~y~%s~s~ da nastaviš s radom.',
  ['spawn_veh'] = 'Stvori vozilo',
  ['spawn_veh_button'] = 'Pritisni ~INPUT_PICKUP~ da pozoves vozilo.',
  ['spawn_truck_button'] = 'Pritisni ~INPUT_PICKUP~ da stvoriš kamion.',
  ['spawn_blocked'] = 'Vozilo blokira spawn lokaciju!',
  ['service_vh'] = 'Vozilo duznost',
  ['return_vh'] = 'Vrati vozilo',
  ['return_vh_button'] = 'Pritisni ~INPUT_PICKUP~ da vratiš vozilo.',
  ['delivery_point'] = 'Lokacija dostave',
  ['delivery'] = 'Dostava',
  ['public_enter'] = 'Pritisni ~INPUT_PICKUP~ da udes u zgradu.',
  ['public_leave'] = 'Pritisni ~INPUT_PICKUP~ da otides na ulaz u zgradu.',

  -- Lumber Jack job
  ['lj_locker_room'] = 'Svlacionica drvosjece',
  ['lj_mapblip'] = 'Šuma',
  ['lj_wood'] = 'Drvo',
  ['lj_pickup'] = 'Pritisni ~INPUT_PICKUP~ da dobijes drvo.',
  ['lj_cutwood'] = 'Sjeca drva',
  ['lj_cutwood_button'] = 'Pritisni ~INPUT_PICKUP~ da presjeces drvo.',
  ['lj_board'] = 'Daske',
  ['lj_planks'] = 'Paket dasaka',
  ['lj_cutwood'] = 'Sjeca drva',
  ['lj_pick_boards'] = 'Pritisni ~INPUT_PICKUP~ da dobijes daske.',
  ['lj_deliver_button'] = 'Pritisni ~INPUT_PICKUP~ da dostavis daske.',

  -- Fisherman
  ['fm_fish_locker'] = 'Svlacionica ribara',
  ['fm_fish'] = 'Riba',
  ['fm_fish_area'] = 'Prostor pecanja',
  ['fm_fish_button'] = 'Pritisni ~INPUT_PICKUP~ da pecaš.',
  ['fm_spawnboat_title'] = 'Stvori brod',
  ['fm_spawnboat'] = 'Pritisni ~INPUT_PICKUP~ da pozoves brod.',
  ['fm_boat_title'] = 'Brod',
  ['fm_boat_return_title'] = 'Vrati brod',
  ['fm_boat_return_button'] = 'Pritisni ~INPUT_PICKUP~ da vratiš brod.',
  ['fm_deliver_fish'] = 'Pritisni ~INPUT_PICKUP~ da dostaviš ribu.',

  -- Fuel
  ['f_oil_refiner'] = 'Svlacionica rafinera',
  ['f_drill_oil'] = 'Buši za naftu',
  ['f_fuel'] = 'Nafta',
  ['f_drillbutton'] = 'Pritisni ~INPUT_PICKUP~ da bušiš.',
  ['f_fuel_refine'] = 'Preradi naftu',
  ['f_refine_fuel_button'] = 'Pritisni ~INPUT_PICKUP~ da preradis.',
  ['f_fuel_mixture'] = 'Izmiksaj preradjenu naftu',
  ['f_gas'] = 'Benzin',
  ['f_fuel_mixture_button'] = 'Pritisni ~INPUT_PICKUP~ da izmiksas benzin.',
  ['f_deliver_gas'] = 'Dostavi benzin',
  ['f_deliver_gas_button'] = 'Pritisni ~INPUT_PICKUP~ da dostavis benzin.',

  -- Miner
  ['m_miner_locker'] = 'Svlacionica rudara',
  ['m_rock'] = 'Kamen',
  ['m_pickrocks'] = 'Pritisni ~INPUT_PICKUP~ da dobis kamenje.',
  ['m_washrock'] = 'Operi kamenje',
  ['m_rock_button'] = 'Pritisni ~INPUT_PICKUP~ da operes kamenje.',
  ['m_rock_smelting'] = 'Taljenje kamenja',
  ['m_copper'] = 'Bakar',
  ['m_sell_copper'] = 'Prodavac bakra',
  ['m_deliver_copper'] = 'Pritisni ~INPUT_PICKUP~ da dostavis bakar.',
  ['m_iron'] = 'Metal',
  ['m_sell_iron'] = 'Prodavac metala',
  ['m_deliver_iron'] = 'Pritisni ~INPUT_PICKUP~ da dostavis metal.',
  ['m_gold'] = 'Zlato',
  ['m_sell_gold'] = 'Prodavac Zlata',
  ['m_deliver_gold'] = 'Pritisni ~INPUT_PICKUP~ da dostavis zlato.',
  ['m_diamond'] = 'Dijamant',
  ['m_sell_diamond'] = 'Prodavac dijamanata',
  ['m_deliver_diamond'] = 'Pritisni ~INPUT_PICKUP~ da dostavis dijamant.',
  ['m_melt_button'] = 'Pritisni ~INPUT_PICKUP~ da pocnes taljenje kamenja.',

  -- Reporter
  ['reporter_name'] = 'Balkan Times',
  ['reporter_garage'] = 'Pritisni ~INPUT_PICKUP~ da otides u garažu.',

  -- Slaughterer
  ['s_slaughter_locker'] = 'Svlacionica mesara',
  ['s_hen'] = 'Kokošja juha',
  ['s_alive_chicken'] = 'Kokoš',
  ['s_catch_hen'] = 'Pritisni ~INPUT_PICKUP~ da uhvatiš kokoš.',
  ['s_slaughtered_chicken'] = 'Ubijena kokoš',
  ['s_chop_animal'] = 'Pritisni ~INPUT_PICKUP~ da sjeces kokoš.',
  ['s_slaughtered'] = 'Kuca mesara',
  ['s_package'] = 'Pakiranje',
  ['s_packagechicken'] = 'Zapakirana kokoš',
  ['s_unpackaged'] = 'Kokoš za pakiranje',
  ['s_unpackaged_button'] = 'Pritisni ~INPUT_PICKUP~ da stavis kokoš u pakiranje.',
  ['s_deliver'] = 'Pritisni ~INPUT_PICKUP~ da dostaviš kokoš.',

  -- Dress Designer
  ['dd_dress_locker'] = 'Svlacionica krojaca',
  ['dd_wool'] = 'Vuna',
  ['dd_pickup'] = 'Pritisni ~INPUT_PICKUP~ da dobite vunu.',
  ['dd_fabric'] = 'Pamuk',
  ['dd_makefabric'] = 'Pritisni ~INPUT_PICKUP~ da napraviš pamuk.',
  ['dd_clothing'] = 'Odjelo',
  ['dd_makeclothing'] = 'Pritisni ~INPUT_PICKUP~ da dobijes odjelo.',
  ['dd_deliver_clothes'] = 'Pritisni ~INPUT_PICKUP~ da dostavis odjelo.',
 }
