Locales['hr'] = {
  -- cloakroom
  ['cloakroom_menu'] = 'Soba za presvlacenje',
  ['cloakroom_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da promijenite ~y~odjeću~s~.',
  ['wear_citizen'] = 'Civilna odjeća',
  ['wear_work'] = 'Radna odjeća',

  -- garage
  ['spawner_prompt'] = 'Pritisnite ~INPUT_CONTEXT~ da pristupite ~y~garaži~s~.',
  ['store_veh'] = 'Pritisnite ~INPUT_CONTEXT~ da spremite vozilo',
  ['spawn_veh'] = 'Spawn auta',
  ['spawnpoint_blocked'] = 'Spawn mjesto je zauzeto molimo da maknete auta!',
  ['only_taxi'] = 'Možete pohraniti samo taksije.',

  ['taking_service'] = 'Šlep služba: Taxi/Uber',
  ['full_service'] = 'Cijeli serveis: ',
  ['amount_invalid'] = 'Nevažeća kolicina',
  ['press_to_open'] = 'Pritisnite ~INPUT_CONTEXT~ da otvorite meni',
  ['billing'] = 'Plaćanje',
  ['billing_sent'] = 'Klijent je primio racun!',
  ['invoice_amount'] = 'Iznos racuna',
  ['no_players_near'] = 'Igrac nije u blizini',
  ['start_job'] = 'Zapocnite / prekinite npc posao',
  ['drive_search_pass'] = 'Vožnja u potrazi za ~y~klijenta',
  ['customer_found'] = 'Vi ste ~g~našli~s~ klijenta, približite mu se',
  ['client_unconcious'] = 'Vaš klijent je  ~r~onesvješten~s~, pronađite nekog drugog',
  ['arrive_dest'] = 'Vi ste ~g~stigli~s~ na vašu destinaciju',
  ['take_me_to_near'] = '~s~Pokupite me blizu sam~y~ %s~s~, near ~y~%s',
  ['take_me_to'] = '~s~Pokupite me ~y~%s',
  ['close_to_client'] = 'Previše ste udaljeni od klijenta, približite mu se',
  ['return_to_veh'] = 'Molimo vratite vozilo kako biste nastavili misiju',
  ['must_in_taxi'] = 'Morate biti u ~y~taxiu~s~ da biste pokrenuli misiju',
  ['must_in_vehicle'] = 'Morate zapoceti misiju u autu',
  ['have_earned'] = 'Zaradili ste ~g~$%s~s~',
  ['comp_earned'] = '- Vaša tvrtka je zaradila ~g~$%s~s~\n- Zaradili ste ~g~$%s~s~',
  ['deposit_stock'] = 'Stavite zalihu',
  ['take_stock'] = 'Uzmite zalihu',
  ['boss_actions'] = 'Šefofa akcija',
  ['mission_complete'] = 'Misija završena',
  ['quantity'] = 'Kolicina',
  ['quantity_invalid'] = 'Nepostojeca kolicina!',
  ['inventory'] = 'Inventar',
  ['taxi_client'] = 'Klijent',
  ['have_withdrawn'] = 'Povukli ste se ~y~x%s~s~ ~b~%s~s~',
  ['have_deposited'] = 'Vi ste ostavili ~y~x%s~s~ ~b~%s~s~',
  ['player_cannot_hold'] = 'Vi ~r~nemate~s~ dovoljno ~y~slobodnog prostora~s~ u Vašem inventaru!',
  ['blip_taxi'] = 'Taxi',
  ['phone_taxi'] = 'Taxi',
}